

flag_model_path: 'BAAI/bge-large-en-v1.5'
tokenizer_name_or_path: "Qwen/Qwen2.5-7B/"

#Game
data_file_path: "./data/dataset/Video_Games/RL/train.jsonl"
id2meta_path: './data/dataset/Video_Games/Retrieval/meta.json'
text_emb_path: './data/dataset/Video_Games/Retrieval/meta.embeddings.npy'
item_emb_path: './data/dataset/Video_Games/Retrieval/embeddings.npy'

##ML-1M
#data_file_path: "./data/dataset/ML-1M/RL/train.jsonl"
#id2meta_path: './data/dataset/ML-1M/Retrieval/meta.json'
#text_emb_path: './data/dataset/ML-1M/Retrieval/meta.embeddings.npy'
#item_emb_path: './data/dataset/ML-1M/Retrieval/embeddings.npy'



device: 'cuda'

log_dir: "./log/reward"
log_file: "reward.log"
topk: 10
item_split_identifier: "\n"



format_error: -1
outcome_error: 0
outcome_correct: 1
outcome_linear: 0.2
recall_num_base: 0.5
recall_num_max: 3
diversity_base: 0.2
sim_reward_base: 10


stage: "cold" # "cold" or "rec"

